### ISSUE TITLE
Invalid language object with tree-sitter v0.21 - caused by NAPI?

### ISSUE THREAD

**Issue by rien** [tree-sitter/node-tree-sitter#193]
I tried updating to tree-sitter 0.21 for our project https://github.com/dodona-edu/dolos/tree/main/parsers which builds a collection of parsers to be used in our tool. We do this by importing each parser as a submodule and using a simple [`binding.gyp`](https://github.com/dodona-edu/dolos/blob/main/parsers/binding.gyp) including the gyp-files of each parser.

This worked fine with the node package of tree-sitter 0.20.6. With the latest release 0.21.0, building using `node-gyp` succeeds, but actually using the parser fails.

Consider the following snippet:

```js
import { java } from "@dodona/dolos-parsers";
import { default as Parser } from "tree-sitter";

const parser = new Parser();
parser.setLanguage(java);
// throws Uncaught TypeError: Invalid language object
//    at Parser.setLanguage (/home/rien/repos/dolos/node_modules/tree-sitter/index.js:338:17)
```

Which is thrown on line 338 in `index.js`, calling the `setLanguage` function from the native `tree-sitter_runtime` binding: 
https://github.com/tree-sitter/node-tree-sitter/blob/2bdc76a15f462d3f394c5598c37f744d415089d4/index.js#L329-L345

I noticed in the commits between https://github.com/tree-sitter/node-tree-sitter/compare/v0.20.6...v0.21.0 that the bindings were changed to NAPI instead of Node. I guess this might be caused by this refactor?

Does anything need to be changed to the parsers themselves to work with NAPI? Is this something that I could fix in my `binding.gyp` or will this require changes in the parsers?

**Comment by gustavotoyota** [comment]
Same here. All languages I've tested (JS, TS and TSX) failed to load with "Invalid language object". Downgrading to 0.20.6 solved the problem.

**Comment by verhovsky** [comment]
With node-tree-sitter 0.21.0, the bindings switch to NAPI instead of NaN #190, so you need to change the binding.cc file of all the languages you want to use to be a NAPI binding.cc file. If you have just a normal binding.cc right now then you can update your `tree-sitter` CLI (`brew upgrade tree-sitter` on macOS) then go to that language's repo/directory and regenerate it like this

```sh
tree-sitter generate
```

If you've made changes to your language's binding.cc file previously, you will have to port those changes to NAPI after re-generating the file. This command also now generates more bindings for other programming languages, by the way, which you may or may not want to keep. This has been done for some languages in the tree-sitter org, you can see how it was done for [tree-sitter-python](https://github.com/tree-sitter/tree-sitter-python/commit/0f9047c857ed0990931b1f899c7d3bf403703147#diff-300f84bb1540d7993e6f8aa7a5e70975414d4f590dc835a06d8e6c41e0f522ab) or for [tree-sitter-bash](https://github.com/tree-sitter/tree-sitter-bash/commit/664c27427ad041daac3c9ec0392c1fdc05a57f31#diff-300f84bb1540d7993e6f8aa7a5e70975414d4f590dc835a06d8e6c41e0f522ab). Like I said, it's just re-running `tree-sitter generate` and re-compiling.

By the way, with 0.21 there's also a handful of backwards incompatible changes to make the Node and Wasm bindings interchangeable (crazy, but they weren't before), namely in Node `SyntaxNode.hasChanges`, `.hasError` and `.isMissing` become properties instead of methods. See https://github.com/tree-sitter/tree-sitter/pull/3103

**Comment by ahelwer** [comment]
@verhovsky my tree-sitter grammar uses the NAPI binding.cc file but still fails with the same error: https://github.com/tlaplus-community/tree-sitter-tlaplus

**Comment by segevfiner** [comment]
I started creating a module that should allow loading older grammars using the new node-tree-sitter as a stop-gap solution until they all get updated https://github.com/segevfiner/node-tree-sitter-compat, haven't published it to npm just yet, but I likely will.

**Comment by segevfiner** [comment]
Published https://www.npmjs.com/package/tree-sitter-compat
