### ISSUE TITLE
node siter fails when included in a react based project and webpack >5

### ISSUE THREAD

**Issue by raul1991** [tree-sitter/node-tree-sitter#194]
I am getting the following errors when bundling the whole code via webpack

, Module not found: Error: Can't resolve 'os' in '......../node_modules/node-gyp-build'

**Comment by TijlE-1951707** [comment]
I have a similar issue. I've had trouble with 'fs' before, but that seemed to be related to changes in the latest react tools that disallow server packages such as fs. For the others I get a "BREAKING CHANGE" (see full output).

<details>
<summary>
<ul>
<li> Can't resolve 'fs' </li>
<li> Can't resolve 'path' </li>
<li> Can't resolve 'os' </li>
<li> Can't resolve 'util' </li>
</ul>
</summary>

```txt
Failed to compile.

Module not found: Error: Can't resolve 'fs' in '/path-to-my-app/node_modules/node-gyp-build'
ERROR in ./node_modules/node-gyp-build/node-gyp-build.js 1:9-22
Module not found: Error: Can't resolve 'fs' in '/path-to-my-app/node_modules/node-gyp-build'

ERROR in ./node_modules/node-gyp-build/node-gyp-build.js 2:11-26
Module not found: Error: Can't resolve 'path' in '/path-to-my-app/node_modules/node-gyp-build'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "path": false }

ERROR in ./node_modules/node-gyp-build/node-gyp-build.js 3:9-22
Module not found: Error: Can't resolve 'os' in '/path-to-my-app/node_modules/node-gyp-build'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "os": require.resolve("os-browserify/browser") }'
	- install 'os-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "os": false }

ERROR in ./node_modules/tree-sitter/index.js 10:13-28
Module not found: Error: Can't resolve 'util' in '/path-to-my-app/node_modules/tree-sitter'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
	- install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "util": false }

webpack compiled with 4 errors
```

**Comment by verhovsky** [comment]
First of all, if you want to use tree-sitter in the browser, you should be using `tree-sitter-web` on npm, not `tree-sitter` (which is what this repo is), because node-tree-sitter is native software. You can't run native software in a web browser. `web-tree-sitter` is Wasm, which you can run in the browser.

Anyway, for using tree-sitter-web, in my webpack I had to add these lines

```js
  resolve: {
    fallback: {
      path: require.resolve('path-browserify'),
      fs: false,
      stream: require.resolve("stream-browserify"),
      util: require.resolve("util/"),
      url: require.resolve("url/"),
      querystring: require.resolve("querystring-es3"),
      string_decoder: require.resolve("string_decoder/"),
      buffer: require.resolve("buffer/")
    }
  },
```

I don't remember which ones are specific to node-tree-sitter and which are related to other code in my project but `fs: false` for sure is

https://github.com/curlconverter/curlconverter.github.io/blob/14c0f13f9b04bb9b06433a1665d5d7c25215608a/webpack.config.js#L122-L133

I think you will need to eject from react to get a webpack config file

```sh
npm run eject
```

**Comment by segevfiner** [comment]
This is a module for Node.js, not the browser, and you webpack config seems to be for the browser or it should have included code/plugin to keep Node.js builtin modules as external. You can use `web-tree-sitter` in the browser.

**Comment by TijlE-1951707** [comment]
Apologies, I received an answer through mail via github (from Boris), but his answer is not here apparently -- not sure why. He redirected me to `web-tree-sitter`, where I created [an issue](https://github.com/tree-sitter/tree-sitter/issues/3195) because I get `need to see wasm magic number` :-) He also helped me with its setup saying that I'd need to change my webconfig. I ended up with this to have it working:

```
    ... 
        }),
        // This is only used in production mode
        new CssMinimizerPlugin(),
      ],
    },
    resolve: {
      fallback: {
        fs: false,
        path: require.resolve('path-browserify'),
      },
    ...
```
