### ISSUE TITLE
parseTextBufferSync error with Atom TextBuffer

### ISSUE THREAD

**Issue by dschwen** [tree-sitter/node-tree-sitter#59]
```
parseTextBufferSync(editor.getBuffer(), tree)
```

throws an error `Uncaught (in promise) TypeError: buffer.getSnapshot is not a function` [here](https://github.com/tree-sitter/node-tree-sitter/blob/8a2987eaa115c867afd6b86920f02c6a4747516a/index.js#L317). `editor.getBuffer()` returns a `TextBuffer` object, but it does not have a `getSnapshot()` method. I've looked and found `getSnapshot` mentioned in the super string interface, but not in Atom's `TextBuffer` object. Are we talking about a different TextBuffer here?

**Comment by maxbrunsfeld** [comment]
Yes, `parseTextBufferSync` takes a superstring text buffer, which is available as a private field of the Atom `TextBuffer`.

**Comment by dschwen** [comment]
Uhm, wait, its either *available* or ts *private*. Or is there a getter? How else would I parse an atom editor buffer?

**Comment by maxbrunsfeld** [comment]
It's private, but this JavaScript, so *private* just means that it's undocumented, and not guaranteed by the Atom team to be API-stable.

Are you doing this in Atom? Or are you using the `text-buffer` library in your own application? I'm going to close this out, since I don't think there is an issue with this library.
